#!/usr/bin/env bash

# File path to store the PID of the gui server process
PID_FILE="scripts/servers/web_gui/server.pid"

if [[ -f config/DarkMessenger.config ]]; then
  source ./config/DarkMessenger.config
else
  echo 'Starting with default config. Edit ./config/DarkMessenger.config if you want custom config'
fi

if [ "$1" == "stop" ]; then
   source scripts/servers/web_gui/server_functions.sh
   stop_gui_server
   exit
fi


if [ -v USE_WEB_GUI ]; then
  if [ ! -v WEB_GUI_PORT ]; then
    WEB_GUI_PORT=9080;
  fi
  source scripts/servers/web_gui/server_functions.sh
  start_gui_server;
fi

